#!/usr/bin/env bash
# ─── idkagent LSP Auto-Installer ─────────────────────
# Generated by idkagent. Installs all LSP servers used by the agent.

set -e

echo "🔧 idkagent LSP Auto-Installer"
echo "================================"

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── TypeScript (tsc) ───────────────────────────────
echo ""
echo "📦 TypeScript (tsc)"
echo "   TypeScript compiler diagnostics via tsc --noEmit"
if command -v tsc &>/dev/null; then
  echo "   ✅ Already installed."
else
  echo "   ⏳ Installing..."
  npm install -g typescript 2>&1 | sed 's/^/   /'
  echo "   ✅ Installation complete."
fi

# ─── Java (JDT LS) ───────────────────────────────
echo ""
echo "📦 Java (JDT LS)"
echo "   Eclipse JDT Language Server for Java diagnostics"
if command -v jdtls &>/dev/null; then
  echo "   ✅ Already installed."
else
  echo "   ⚠️  jdtls not found in PATH."
  echo "   JDT LS cannot be auto-installed. Please follow manual instructions:"
  echo "   https://github.com/eclipse-jdtls/eclipse.jdt.ls"
  echo ""
  echo "   Quick guide:"
  echo "     1. Download from https://download.eclipse.org/jdtls/milestones/"
  echo "     2. Extract to ~/jdtls"
  echo "     3. Create a symlink: ln -sf ~/jdtls/bin/jdtls ~/.local/bin/jdtls"
fi

echo ""
echo "✅ All LSP servers installed/verified."
echo ""
echo "LSP configuration is in config.yml under 'lsp:'"
echo "Run: idkagent lsp list"
