import fs from 'node:fs';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { loadConfig, type AgentConfig, type LspToolConfig } from './config.js';

// ─── LSP Definitions ─────────────────────────────────────────

export interface LspDefinition {
  name: string;
  displayName: string;
  bin: string;
  description: string;
  /** How to check if it's installed */
  checkCommand: string;
  /** Shell command to install it (used by install-lsp.sh) */
  installCommand: string;
  /** URL to download page / docs */
  url: string;
}

const KNOWN_LSPS: LspDefinition[] = [
  {
    name: 'typescript',
    displayName: 'TypeScript (tsc)',
    bin: 'tsc',
    description: 'TypeScript compiler diagnostics via tsc --noEmit',
    checkCommand: 'tsc --version',
    installCommand: 'npm install -g typescript',
    url: 'https://www.npmjs.com/package/typescript',
  },
  {
    name: 'java',
    displayName: 'Java (JDT LS)',
    bin: 'jdtls',
    description: 'Eclipse JDT Language Server for Java diagnostics',
    checkCommand: 'jdtls --version 2>/dev/null || echo "not_found"',
    installCommand: '',
    url: 'https://github.com/eclipse-jdtls/eclipse.jdt.ls',
  },
];

export function getKnownLsps(): LspDefinition[] {
  return KNOWN_LSPS;
}

export function getLspByName(name: string): LspDefinition | undefined {
  return KNOWN_LSPS.find(l => l.name === name.toLowerCase());
}

// ─── Status Checks ───────────────────────────────────────────

export function isLspInstalled(lsp: LspDefinition): boolean {
  try {
    execSync(lsp.checkCommand, { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 10_000 });
    return true;
  } catch {
    return false;
  }
}

export function getLspConfig(config: AgentConfig, name: string): LspToolConfig | undefined {
  const lsp = getLspByName(name);
  if (!lsp) return undefined;
  return (config.lsp as Record<string, LspToolConfig | undefined>)[lsp.name];
}

export function isLspEnabled(config: AgentConfig, name: string): boolean {
  const cfg = getLspConfig(config, name);
  return cfg?.enabled ?? false;
}

// ─── Config Updates ──────────────────────────────────────────

export function setLspEnabled(config: AgentConfig, name: string, enabled: boolean): void {
  const lsp = getLspByName(name);
  if (!lsp) return;
  const lspMap = config.lsp as Record<string, LspToolConfig>;
  if (!lspMap[lsp.name]) {
    lspMap[lsp.name] = { bin: lsp.bin, enabled };
  } else {
    lspMap[lsp.name].enabled = enabled;
  }
}

// ─── Install / Uninstall via Script ─────────────────────────

export function installLsp(lsp: LspDefinition): { success: boolean; output: string } {
  if (lsp.name === 'java') {
    return {
      success: false,
      output: `Java JDT LS cannot be auto-installed. Please follow manual instructions:\n  ${lsp.url}\n\nAfter installing, ensure 'jdtls' is available in your PATH.`,
    };
  }

  if (!lsp.installCommand) {
    return { success: false, output: `No install command available for ${lsp.displayName}.` };
  }

  try {
    const output = execSync(lsp.installCommand, {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: 120_000,
    });
    return { success: true, output: output.trim() || `✅ ${lsp.displayName} installed successfully.` };
  } catch (err: any) {
    return {
      success: false,
      output: err.stderr?.toString() || err.stdout?.toString() || err.message || 'Unknown error',
    };
  }
}

export function uninstallLsp(lsp: LspDefinition): { success: boolean; output: string } {
  let uninstallCmd: string;
  if (lsp.name === 'typescript') {
    uninstallCmd = 'npm uninstall -g typescript';
  } else {
    return { success: false, output: `Auto-uninstall not supported for ${lsp.displayName}. Please remove it manually.` };
  }

  try {
    const output = execSync(uninstallCmd, {
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: 60_000,
    });
    return { success: true, output: output.trim() || `✅ ${lsp.displayName} uninstalled.` };
  } catch (err: any) {
    return {
      success: false,
      output: err.stderr?.toString() || err.stdout?.toString() || err.message || 'Unknown error',
    };
  }
}

// ─── Generate install script ─────────────────────────────────

export function getInstallScriptContent(): string {
  const lsps = KNOWN_LSPS;
  const parts: string[] = [];
  parts.push(`#!/usr/bin/env bash`);
  parts.push(`# ─── idkagent LSP Auto-Installer ─────────────────────`);
  parts.push(`# Generated by idkagent. Installs all LSP servers used by the agent.`);
  parts.push(``);
  parts.push(`set -e`);
  parts.push(``);
  parts.push(`echo "🔧 idkagent LSP Auto-Installer"`);
  parts.push(`echo "================================"`);
  parts.push(``);
  parts.push(`INSTALL_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"`);
  parts.push(``);

  for (const lsp of lsps) {
    parts.push(`# ─── ${lsp.displayName} ───────────────────────────────`);
    parts.push(`echo ""`);
    parts.push(`echo "📦 ${lsp.displayName}"`);
    parts.push(`echo "   ${lsp.description}"`);
    parts.push(`if command -v ${lsp.bin} &>/dev/null; then`);
    parts.push(`  echo "   ✅ Already installed."`);
    if (lsp.installCommand) {
      parts.push(`else`);
      parts.push(`  echo "   ⏳ Installing..."`);
      parts.push(`  ${lsp.installCommand} 2>&1 | sed 's/^/   /'`);
      parts.push(`  echo "   ✅ Installation complete."`);
    }
    parts.push(`fi`);
    parts.push(``);
  }

  parts.push(`echo ""`);
  parts.push(`echo "✅ All LSP servers installed/verified."`);
  parts.push(`echo ""`);
  parts.push(`echo "LSP configuration is in config.yml under 'lsp:'"`);
  parts.push(`echo "Run: idkagent lsp list"`);
  parts.push(``);
  return parts.join('\n');
}
